yarn add -D \
    @babel/core \
    @babel/plugin-proposal-class-properties \
    @babel/plugin-proposal-decorators \
    @babel/plugin-syntax-dynamic-import \
    @babel/plugin-transform-arrow-functions \
    @babel/preset-env \
    @babel/preset-typescript \
    babel-loader \
    cache-loader \
    copy-webpack-plugin \
    html-loader \
    html-webpack-plugin \
    prettier \
    rollup \
    rollup-plugin-babel \
    rollup-plugin-commonjs \
    rollup-plugin-lit-css \
    rollup-plugin-livereload \
    rollup-plugin-node-resolve \
    rollup-plugin-postcss \
    rollup-plugin-serve \
    rollup-plugin-terser \
    rollup-plugin-uglify \
    thread-loader \
    typescript \
    webpack \
    webpack-cli \
    webpack-dev-server \
    whatwg-fetch \
    workbox-webpack-plugin \
    worker-loader \
    @babel/plugin-syntax-import-meta \
    rollup-plugin-replace \
    rollup-plugin-copy \

yarn add \
    @webcomponents/webcomponentsjs \
    core-js \
    lit-element \
    pwa-helpers \
    redux \
    redux-thunk \
